database:
  host: localhost
  port: 5432
  user: your_db_user
  password: your_db_password
  name: your_db_name

kafka:
  brokers:
    - localhost:9092
  topic: job-execution

worker:
  max_concurrent_jobs: 5
  retry_limit: 3
  heartbeat_interval: 5s

logging:
  level: info
  format: json
  output: stdout